"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { Brand } from "@/components/Brand";
import { SiteFooter } from "@/components/SiteChrome";
type Row={id:string;submitted_at:string;model:string;responsible?:{fullName?:string};company?:{legalName?:string;tradeName?:string;sector?:string};services?:string[];notification_status?:string};
export default function BalcaoPage(){
 const [rows,setRows]=useState<Row[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/interno/submissions").then(async r=>{if(r.status===401){window.location.href="/interno";return}const j=await r.json();if(!r.ok)throw new Error(j.error);setRows(j.data||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 async function logout(){await fetch("/api/interno/logout",{method:"POST"});window.location.href="/";}
 return <main className="acjl-page"><header className="acjl-top"><Link href="/" aria-label="ACJL - página inicial"><Brand compact/></Link><div className="internal-header-actions"><Link href="/" className="internal-back">Voltar</Link><button onClick={logout} className="internal-logout">Sair</button></div></header><div className="acjl-wrap internal-dashboard"><div className="internal-dashboard-head"><div><div className="acjl-eyebrow">OPORTUNIDADES RECEBIDAS</div><h1>Diagnósticos</h1><p>Acompanhe os pedidos recebidos e prepare o próximo passo comercial.</p></div><div className="internal-count">{rows.length}<span>diagnósticos</span></div></div>{loading?<div className="acjl-card internal-empty">A carregar diagnósticos…</div>:error?<div className="form-error">{error}</div>:rows.length===0?<div className="acjl-card internal-empty"><strong>Ainda não há diagnósticos recebidos.</strong><p>Quando um prospect concluir o formulário, o registo aparecerá aqui.</p></div>:<div className="internal-list">{rows.map(r=><article className="acjl-card internal-lead" key={r.id}><div className="internal-lead-main"><div className="internal-lead-top"><span className="status-pill">{r.model==="AVENCA"?"Avença mensal":"Serviço pontual"}</span><small>{new Date(r.submitted_at).toLocaleString("pt-MZ")}</small></div><h2>{r.company?.tradeName||r.company?.legalName||"Empresa sem nome"}</h2><p>{r.company?.sector||"Sector não indicado"} · {r.responsible?.fullName||"Responsável não indicado"}</p><div className="internal-tags">{(r.services||[]).map(s=><span key={s}>{s}</span>)}</div></div><div className="internal-lead-status"><span className={r.notification_status==="sent"?"status-dot sent":"status-dot"}></span>{r.notification_status==="sent"?"Notificado":"Pendente"}</div></article>)}</div>}</div><SiteFooter/></main>}
