import Link from "next/link";
import { Brand } from "@/components/Brand";
import { SiteFooter } from "@/components/SiteChrome";

const models=[
 {n:"01",title:"Avença mensal",text:"Para necessidades contínuas, com acompanhamento regular e uma solução ajustada à realidade da empresa.",items:["Gestão Fiscal e de Impostos","Contabilidade","Processamento de Salários","Assistência Administrativa"]},
 {n:"02",title:"Requisições de serviços",text:"Para necessidades pontuais, sem compromisso mensal. Solicite o serviço quando precisar.",items:["Serviços fiscais e contabilísticos","Auditorias","Treinamentos","Serviços especializados"]},
 {n:"03",title:"Solução dimensionada",text:"O diagnóstico ajuda a ACJL a compreender o esforço necessário antes de definir a solução comercial.",items:["Necessidades da empresa","Volume e complexidade","Modelo de contratação","Proposta adequada"]}
];
export default function HomePage(){return <main className="acjl-page">
 <header className="acjl-top"><Link href="/" aria-label="ACJL - página inicial"><Brand compact/></Link><Link href="/interno" className="internal-access">Acesso Restrito</Link></header>
 <section className="acjl-wrap acjl-landing-hero"><div className="landing-copy"><div className="acjl-eyebrow">DIAGNÓSTICO EMPRESARIAL</div><h1 className="acjl-title">Conheça a realidade da sua empresa.</h1><p className="acjl-copy landing-description">Conte-nos como a sua empresa funciona, o que precisa e onde procura apoio. Com esta informação, a ACJL poderá preparar uma solução mais adequada à sua realidade.</p><div className="landing-actions"><Link className="acjl-button acjl-primary" href="/diagnostico/inicio">Começar diagnóstico <span>→</span></Link><span className="landing-time">5–10 minutos · sem documentos nesta etapa</span></div></div></section>
 <section className="acjl-wrap roadmap-section"><div className="section-heading"><div><div className="acjl-eyebrow">COMO PODEMOS TRABALHAR CONSIGO</div><h2>Uma solução que acompanha a sua necessidade.</h2></div><p>O diagnóstico não é uma contratação. É o ponto de partida para perceber qual modelo faz sentido para a sua empresa.</p></div><div className="roadmap-grid">{models.map(m=><article className="roadmap-card" key={m.n}><div className="roadmap-number">{m.n}</div><h3>{m.title}</h3><p>{m.text}</p><ul>{m.items.map(i=><li key={i}>{i}</li>)}</ul></article>)}</div></section>
 <section className="acjl-wrap benefit-section"><div className="benefit-panel"><div><div className="acjl-eyebrow">O QUE GANHA COM O DIAGNÓSTICO</div><h2>Um serviço sob medida. Sem surpresas no caminho. Transparência desde o início.</h2></div><div className="benefit-list"><div><strong>Compreensão da realidade</strong><p>A ACJL conhece o contexto antes de dimensionar o atendimento.</p></div><div><strong>Serviço ajustado</strong><p>As necessidades identificadas orientam os serviços a considerar.</p></div><div><strong>Flexibilidade</strong><p>A solução pode ser contínua, pontual ou especializada.</p></div></div></div></section>
 <SiteFooter/>
 </main>}