"use client";
import Link from "next/link";import{useState}from"react";import{SiteHeader,SiteFooter}from"@/components/SiteChrome";import{readDiagnostic,saveDiagnostic}from"@/lib/diagnostic";
export default function Empresa(){const[d,setD]=useState(readDiagnostic());const u=(k:string,v:string)=>setD(x=>({...x,company:{...x.company,[k]:v}}));const next=()=>saveDiagnostic(d);
return <main className="acjl-page"><SiteHeader step="2 DE 4 · EMPRESA · 1/3"/><div className="acjl-wrap diagnostic-shell"><div className="acjl-form"><div className="acjl-progress"><span style={{width:"33%"}}/></div><div className="diagnostic-intro"><div><div className="acjl-eyebrow">ETAPA 2 · EMPRESA</div><h1>Agora, vamos conhecer a empresa.</h1><p>Estes dados ajudam a ACJL a compreender a dimensão e o contexto do trabalho antes de definir uma solução.</p></div></div><section className="acjl-card diagnostic-card">
<div className="acjl-field"><label>Nome legal da empresa</label><input className="acjl-input" value={d.company.legalName} onChange={e=>u("legalName",e.target.value)} placeholder="Ex.: Empresa, Lda."/></div>
<div className="acjl-field"><label>Nome comercial <span>(se aplicável)</span></label><input className="acjl-input" value={d.company.tradeName} onChange={e=>u("tradeName",e.target.value)}/></div>
<div className="acjl-field"><label>NUIT</label><input className="acjl-input" value={d.company.nuit} onChange={e=>u("nuit",e.target.value)} placeholder="NUIT da empresa"/></div>
<div className="acjl-field"><label>Tipo de entidade</label><select className="acjl-select" value={d.company.organizationType} onChange={e=>u("organizationType",e.target.value)}><option value="">Seleccione</option><option>Sociedade por Quotas</option><option>Sociedade Anónima</option><option>Empresário em Nome Individual</option><option>ONG / Organização sem fins lucrativos</option><option>Outra</option></select></div>
<div className="acjl-field"><label>Sector de actividade</label><select className="acjl-select" value={d.company.sector} onChange={e=>u("sector",e.target.value)}><option value="">Seleccione</option><option>Comércio</option><option>Construção</option><option>Serviços</option><option>Indústria</option><option>Agricultura</option><option>Transportes e Logística</option><option>Turismo e Hotelaria</option><option>Educação</option><option>Saúde</option><option>ONG / Desenvolvimento</option><option>Outro</option></select></div>
<div className="acjl-field"><label>Actividade principal</label><input className="acjl-input" value={d.company.mainActivity} onChange={e=>u("mainActivity",e.target.value)} placeholder="O que a empresa faz principalmente?"/></div>
<div className="acjl-field"><label>Descrição da actividade</label><textarea rows={3} className="acjl-textarea" value={d.company.activityDescription} onChange={e=>u("activityDescription",e.target.value)} placeholder="Descreva brevemente como a empresa opera."/></div>
<div className="acjl-field"><label>Ano de constituição</label><input className="acjl-input" inputMode="numeric" value={d.company.incorporationYear} onChange={e=>u("incorporationYear",e.target.value)} placeholder="Ex.: 2022"/></div>
<div className="acjl-field"><label>Ano de início efectivo da actividade</label><input className="acjl-input" inputMode="numeric" value={d.company.activityStartYear} onChange={e=>u("activityStartYear",e.target.value)} placeholder="Ex.: 2023"/></div>
<div className="acjl-field"><label>Sede / localização principal</label><input className="acjl-input" value={d.company.location} onChange={e=>u("location",e.target.value)} placeholder="Cidade / Província"/></div>
<div className="acjl-field"><label>Número de estabelecimentos</label><select className="acjl-select" value={d.company.establishments} onChange={e=>u("establishments",e.target.value)}><option value="">Seleccione</option><option>1</option><option>2</option><option>3 a 5</option><option>Mais de 5</option></select></div>
<div className="acjl-field"><label>Número aproximado de colaboradores</label><select className="acjl-select" value={d.company.employeeRange} onChange={e=>u("employeeRange",e.target.value)}><option value="">Seleccione</option><option>1 a 5</option><option>6 a 10</option><option>11 a 20</option><option>21 a 50</option><option>51 a 100</option><option>Mais de 100</option><option>Não sei</option></select></div>
<div className="acjl-field"><label>Volume de actividade</label><select className="acjl-select" value={d.company.activityVolume} onChange={e=>u("activityVolume",e.target.value)}><option value="">Seleccione</option><option>Baixo</option><option>Moderado</option><option>Elevado</option><option>Varia significativamente</option><option>Não sei</option></select></div>
<div className="acjl-actions"><Link className="acjl-button acjl-secondary" href="/diagnostico/responsavel">← Voltar</Link><Link onClick={next} className="acjl-button acjl-primary" href="/diagnostico/necessidades">Continuar →</Link></div>
</section></div></div><SiteFooter/></main>}